# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2023 ETH Zurich.

status = ["setup-and-test - macos-latest", "setup-and-test - ubuntu-latest", "setup-and-test - windows-latest"]
timeout_sec = 7200
